### ISSUE TITLE
bug in simul_negbin 

### ISSUE THREAD

**Issue by stephens999** [hansenlab/tricycle_paper_figs#1]
I think there is a bug in simul_negbin (eg in the file sfig.nbsimulationLibrary.R and others).
Specifically I think the term lambda / colSums(lambda) in
lambda_scaled <- sweep(lambda / colSums(lambda), MARGIN = 1, STATS = libsizes, FUN = "*")
does not make sense (R processes matrix elements by row first,
and dividing the rows of a matrix by its column sums will
hardly ever make sense.)

Maybe it should be lambda_scaled <- sweep(t(t(lambda) / colSums(lambda)), MARGIN = 1, STATS = libsizes, FUN = "*")

**Comment by sjczheng** [comment]
Dear @stephens999

Thanks so much for the catch.
I am sorry that I did not catch that.
We have now fixed the code and corresponding figures.
The following figures have been updated due to the issue:
https://github.com/hansenlab/tricycle_paper_figs/blob/main/figs/sfigs/sfig.nbsimulationApilitudes.pdf
https://github.com/hansenlab/tricycle_paper_figs/blob/main/figs/sfigs/sfig.nbsimulationLibrary.pdf
https://github.com/hansenlab/tricycle_paper_figs/blob/main/figs/sfigs/sfig.nbsimulationPeaks.pdf
https://github.com/hansenlab/tricycle_paper_figs/blob/main/figs/response_figs/response.2peaksloc.pdf

As you can see, the figures barely change (except for some random variation). 
No conclusion should be changed due to these changes.
We will double-check that we don't have similar bugs in our analyses.

Best,
Shijie

**Comment by stephens999** [comment]
thanks! feel free to close this issue. (I have submitted my review to journal, so you should get
that soon; I did not expect this issue to change results greatly, so it does not really affect my review.)

**Comment by sjczheng** [comment]
Thank you.
